name = "website-hot-tub-store-8"
compatibility_date = "2026-08-01"
compatibility_flags = ["nodejs_compat", "nodejs_als"]

[observability]
enabled = true

[[d1_databases]]
binding = "DB"
database_name = "website-hot-tub-store-8-inventory"
database_id = "755c0c04-02d2-4f97-bac6-4533f81c203a"

[[r2_buckets]]
binding = "PRODUCT_IMAGES"
bucket_name = "website-hot-tub-store-8-images"

[[kv_namespaces]]
binding = "SESSION"
id = "39cd9ffcb3d04f5bb4289f0e0ca006fc"
