name = "website-hot-tub-store-8-preview"
compatibility_date = "2026-08-01"
compatibility_flags = ["nodejs_compat", "nodejs_als"]

[observability]
enabled = true

[[d1_databases]]
binding = "DB"
database_name = "website-hot-tub-store-8-preview-inventory"
database_id = "346d1111-34ba-49ab-80d7-674447290026"

[[r2_buckets]]
binding = "PRODUCT_IMAGES"
bucket_name = "website-hot-tub-store-8-images"

[[kv_namespaces]]
binding = "SESSION"
id = "ca5b7e356be241378868de5126a82d46"
