// Generated by Site Launchpad. Edit in the dashboard and export again.
import type { ClientConfigInput } from "./schema";

export const rawClientConfig: ClientConfigInput = {
  "deployMode": "client",
  "identity": {
    "name": "The Hot Tub Store",
    "shortName": "Hot Tub Store",
    "foundedYear": 2014,
    "tagline": "Premium hot tubs, swim spas, and recovery gear — in stock in Scottsdale.",
    "siteUrl": "https://increaseroasai.com/",
    "schemaType": "Store"
  },
  "contact": {
    "phone": "+14805550180",
    "phoneDisplayOverride": "(480) 555-0180",
    "smsPhone": "+14805550180",
    "email": "hello@thehottubstore.com"
  },
  "address": {
    "street": "18420 N Scottsdale Rd",
    "street2": "Suite 110",
    "city": "Scottsdale",
    "region": "AZ",
    "postalCode": "85255",
    "country": "US",
    "latitude": 33.64652,
    "longitude": -111.89061,
    "googlePlaceId": "ChIJDemoHotTubStoreScottsdaleAZ2014"
  },
  "hours": [
    {
      "days": [
        "Monday"
      ],
      "opens": "10:00",
      "closes": "18:00"
    },
    {
      "days": [
        "Tuesday"
      ],
      "opens": "10:00",
      "closes": "18:00"
    },
    {
      "days": [
        "Wednesday"
      ],
      "opens": "10:00",
      "closes": "18:00"
    },
    {
      "days": [
        "Thursday"
      ],
      "opens": "10:00",
      "closes": "18:00"
    },
    {
      "days": [
        "Friday"
      ],
      "opens": "10:00",
      "closes": "18:00"
    },
    {
      "days": [
        "Saturday"
      ],
      "opens": "09:00",
      "closes": "17:00"
    },
    {
      "days": [
        "Sunday"
      ],
      "opens": "11:00",
      "closes": "16:00"
    }
  ],
  "social": {
    "facebook": "https://www.facebook.com/thehottubstore",
    "instagram": "https://www.instagram.com/thehottubstore",
    "youtube": "https://www.youtube.com/@thehottubstore",
    "tiktok": "https://www.tiktok.com/@thehottubstore",
    "x": "https://x.com/thehottubstore",
    "linkedin": "https://www.linkedin.com/company/the-hot-tub-store",
    "googleBusiness": "https://maps.google.com/?cid=thehottubstorescottsdale"
  },
  "brand": {
    "colors": {
      "primary": "#087F8C",
      "primaryMid": "#066875",
      "deep": "#064F5B",
      "night": "#043A43",
      "abyss": "#02272E",
      "accent": "#45D6C6",
      "accentSoft": "#83E7DC",
      "accentDeep": "#22B7A7",
      "accentDark": "#08766D",
      "accentLift": "#9AF0E7",
      "accentPress": "#20AFA1",
      "accentGlow": "#C5F8F3",
      "urgent": "#D7261E",
      "urgentLight": "#E8382F",
      "urgentDark": "#B71E17",
      "surface": "#FFFFFF",
      "surfaceAlt": "#EFFBFA",
      "ink": "#141927",
      "inkMuted": "#4A5268",
      "onDark": "#D4F5F2",
      "onDarkMuted": "#9BCFC9"
    },
    "fonts": {
      "display": "Plus Jakarta Sans",
      "body": "Manrope",
      "mono": "IBM Plex Mono",
      "googleFontsHref": "https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:wght@400;500;600;700;800&family=Manrope:wght@400;500;600;700&family=IBM+Plex+Mono:wght@400;500;700&display=swap"
    },
    "logos": {
      "nav": "https://pub-987c2295100c458f86a1f7f2be79c41c.r2.dev/clients/8-the-hot-tub-store/astro/navLogo-b0c1f29d812bf89b16eccc33d981668b1b9a242be216bbdb6f090f896da9633e-456585e1f11344ac8b658924d82d1580.webp",
      "footer": "https://pub-987c2295100c458f86a1f7f2be79c41c.r2.dev/clients/8-the-hot-tub-store/astro/footerLogo-b0c1f29d812bf89b16eccc33d981668b1b9a242be216bbdb6f090f896da9633e-a5e57d568e294edab891dd25d58c8229.webp",
      "inventory": "https://pub-987c2295100c458f86a1f7f2be79c41c.r2.dev/clients/8-the-hot-tub-store/astro/inventoryLogo-b0c1f29d812bf89b16eccc33d981668b1b9a242be216bbdb6f090f896da9633e-6ab031c5c649459c9be84ec3b3f5a356.webp",
      "favicon": "https://pub-987c2295100c458f86a1f7f2be79c41c.r2.dev/clients/8-the-hot-tub-store/astro/favicon-2833e9c283f998e0861fecc1571182b94f022b52c4c90c80cc2fefc807f35e3a-e4eda3da34234aa4a353a50e4e7a26ee.webp",
      "ogImage": "https://pub-987c2295100c458f86a1f7f2be79c41c.r2.dev/clients/8-the-hot-tub-store/astro/ogImage-030f808ea0b50806e5e07983e5fc1844a2d1bbf2b3382ebde8c63b995fcc9801-7865891bff3147b0a6169fe5e1503894.webp"
    },
    "radius": {
      "card": 24,
      "button": 12,
      "pill": 999
    }
  },
  "nav": {
    "items": [
      {
        "type": "categories"
      },
      {
        "type": "link",
        "label": "Find Your Match",
        "href": "/find-your-match",
        "inHeader": true,
        "inFooter": true
      },
      {
        "type": "link",
        "label": "Inventory",
        "href": "/inventory",
        "inHeader": true,
        "inFooter": true
      },
      {
        "type": "link",
        "label": "Financing",
        "href": "/financing",
        "inHeader": true,
        "inFooter": true
      },
      {
        "type": "link",
        "label": "Visit Us",
        "href": "/visit-us",
        "inHeader": true,
        "inFooter": true
      }
    ],
    "primaryCta": {
      "label": "Shop Inventory",
      "href": "/inventory"
    },
    "legalItems": [
      {
        "label": "Privacy Policy",
        "href": "/privacy-policy"
      }
    ]
  },
  "categories": {
    "hot-tub": {
      "enabled": true,
      "label": "Hot Tubs",
      "blurb": "Six-person luxury spas with deep seats, strong jets, and LED lighting — in stock and ready to soak this week.",
      "heroImage": "https://pub-987c2295100c458f86a1f7f2be79c41c.r2.dev/clients/8-the-hot-tub-store/astro/categoryHotTubs-9900f6745c096443dab6d2513054e5d2501ebcafdbdb9d5270aa1e416193dd06-87cd1a4441484567874f9b268a1aacbb.webp",
      "sortOrder": 0
    },
    "swim-spa": {
      "enabled": true,
      "label": "Swim Spas",
      "blurb": "Year-round swim, current training, and a therapy seat in one backyard unit. Come try the current on the floor.",
      "heroImage": "https://pub-987c2295100c458f86a1f7f2be79c41c.r2.dev/clients/8-the-hot-tub-store/astro/categorySwimSpas-6db3d07da59b0f8283eb657e4f0f4b59f0ee32738a4cd3fbc7a1615d9f778560-efad779fae294ac2be0aa8b0477a61fa.webp",
      "sortOrder": 1
    },
    "sauna": {
      "enabled": true,
      "label": "Saunas",
      "blurb": "Indoor cedar infrared and traditional saunas for recovery, sleep, and quiet heat at home.",
      "heroImage": "https://pub-987c2295100c458f86a1f7f2be79c41c.r2.dev/clients/8-the-hot-tub-store/astro/categorySaunas-2db5313c8ec41e7a36574631a286199e2e25f3ec18deb402a8475a250ee715c4-bde3cafe41dc4c0c90677d4a09af4de6.webp",
      "sortOrder": 2
    },
    "cold-plunge": {
      "enabled": true,
      "label": "Cold Plunge",
      "blurb": "Chilled plunge tubs for contrast therapy after a soak, a workout, or a long desert day.",
      "heroImage": "https://pub-987c2295100c458f86a1f7f2be79c41c.r2.dev/clients/8-the-hot-tub-store/astro/categoryColdPlunge-b40482a9495f3ac2494bd2c50229e619a09f6ffb64401a9cd7e466bb0d790068-0ae8107444b84d4292cd5f47758921ca.webp",
      "sortOrder": 3
    },
    "massage-chair": {
      "enabled": true,
      "label": "Massage Chairs",
      "blurb": "Full-body massage chairs for the living room — zero-gravity recline, heat, and stretch programs.",
      "heroImage": "https://pub-987c2295100c458f86a1f7f2be79c41c.r2.dev/clients/8-the-hot-tub-store/astro/categoryMassageChairs-7653ffa8e7632079147d0ee6627395d04fa0818e968ad067de5dc19eacb37db7-a111ca272adb429ba8d3a4dfea23d8ad.webp",
      "sortOrder": 4
    }
  },
  "serviceAreas": [
    "Scottsdale",
    "Phoenix",
    "Paradise Valley",
    "Tempe",
    "Mesa",
    "Chandler",
    "Gilbert",
    "Fountain Hills",
    "Cave Creek",
    "North Scottsdale"
  ],
  "financing": {
    "headline": "Check my options",
    "blurb": "From about $149/month on a mid-size spa after delivery and setup.",
    "bullets": [
      "Promotional financing available on qualifying purchases of $2,500 or more. Terms from 24 to 60 months. Ask the showroom team for today's rates."
    ],
    "lenderName": "Synchrony Home",
    "applyUrl": "https://www.mysynchrony.com/",
    "disclaimer": "Subject to credit approval. Equal Housing Lender. Example payment is an estimate only and is not an offer of credit."
  },
  "display": {
    "showPrice": true,
    "showMonthly": true
  },
  "homepage": {
    "title": null,
    "description": null,
    "sections": [
      {
        "type": "announcement",
        "badge": "Fall Showroom Event",
        "text": "In-stock spas ship this month — free delivery inside Metro Phoenix",
        "href": "/inventory"
      },
      {
        "type": "hero",
        "eyebrow": "Scottsdale showroom",
        "headline": "The backyard soak you can try today",
        "highlight": [
          "try today"
        ],
        "subhead": "Walk a floor of filled hot tubs, swim spas, saunas, and cold plunges. Leave with one out-the-door number — unit, delivery, and setup.",
        "bullets": [
          {
            "text": "Working models on the floor — sit in them before you buy",
            "superlative": false,
            "footnote": null
          },
          {
            "text": "Out-the-door pricing that includes delivery and professional setup",
            "superlative": false,
            "footnote": null
          },
          {
            "text": "Financing from about $149/month on qualifying spas",
            "superlative": false,
            "footnote": null
          }
        ],
        "backgroundImage": "https://pub-987c2295100c458f86a1f7f2be79c41c.r2.dev/clients/8-the-hot-tub-store/assets/hero-9900f6745c096443dab6d2513054e5d2501ebcafdbdb9d5270aa1e416193dd06-d09a972bc03e490698837e09b6bdcb8a.webp",
        "image": null,
        "promo": "Fall event: complimentary delivery and startup chemicals on in-stock spas through October 31.",
        "actions": [
          {
            "label": "Shop inventory",
            "href": "/inventory",
            "style": "primary"
          },
          {
            "label": "Request pricing",
            "href": "/find-your-match",
            "style": "secondary"
          }
        ],
        "leadCard": {
          "heading": "Get today's local price",
          "subtext": "Tell us seats, budget, and backyard access. We'll text current inventory and a written total.",
          "footnote": "What happens next: a specialist texts availability within one business hour. No spam, no hard sell."
        }
      },
      {
        "type": "stats",
        "items": [
          {
            "value": "12+",
            "label": "Years on Scottsdale Rd",
            "claim": null
          },
          {
            "value": "4.9★",
            "label": "Google rating",
            "claim": null
          },
          {
            "value": "48hr",
            "label": "Typical in-stock delivery",
            "claim": null
          },
          {
            "value": "100%",
            "label": "Written out-the-door price",
            "claim": null
          }
        ]
      },
      {
        "type": "offercard",
        "eyebrow": "Open 7 days in North Scottsdale",
        "heading": "There has never been a better week to sit in one",
        "body": "Every spa on the floor is filled and running. Compare jets, seating, and insulation with someone who installs these every week.",
        "bullets": [
          {
            "text": "Sit in working models before you spend a dollar",
            "superlative": false,
            "footnote": null
          },
          {
            "text": "One written price: spa, delivery, crane if needed, and startup",
            "superlative": false,
            "footnote": null
          },
          {
            "text": "Flexible financing for most credit profiles",
            "superlative": false,
            "footnote": null
          },
          {
            "text": "Local water-care and service after the sale",
            "superlative": false,
            "footnote": null
          }
        ],
        "actions": [
          {
            "label": "See what's in stock",
            "href": "/inventory",
            "style": "primary"
          },
          {
            "label": "Plan a showroom visit",
            "href": "/visit-us",
            "style": "secondary"
          }
        ]
      },
      {
        "type": "products",
        "eyebrow": "In stock · no factory wait",
        "heading": "Showroom selection",
        "body": "These are units you can sit in today. Ask about current availability, covers, and steps.",
        "limit": 6,
        "category": null,
        "moreLink": {
          "label": "See the full floor",
          "href": "/inventory",
          "style": "primary"
        },
        "disclaimer": "Photos are representative. Serial numbers, options, and pricing are confirmed in the showroom."
      },
      {
        "type": "categories",
        "eyebrow": "Shop by ritual",
        "heading": "What are you adding to the backyard?",
        "body": "Hot tubs for nights in, swim spas for training, saunas and plunges for recovery, chairs for the den.",
        "showImages": true
      },
      {
        "type": "imagecards",
        "eyebrow": "Every line we sell is on the floor in Scottsdale. Pick a path or walk them all.",
        "heading": "Start with the right category",
        "items": [
          {
            "title": "Hot Tubs",
            "body": "Deep seats, 40–70 jets, and covers rated for desert sun.",
            "image": "https://pub-987c2295100c458f86a1f7f2be79c41c.r2.dev/clients/8-the-hot-tub-store/assets/hotTubs-e8496d6c8987e896d4eb0eaf12e0b7efaecfeaf9d7b280adac9b11b005f89d62-df153e3395c242a199a2bbafa95d7041.webp",
            "href": "/hot-tubs"
          },
          {
            "title": "Swim Spas",
            "body": "Swim current plus a therapy seat — no pool required.",
            "image": "https://pub-987c2295100c458f86a1f7f2be79c41c.r2.dev/clients/8-the-hot-tub-store/assets/swimSpas-e608505c26840a904e2b33af294ccf59401e3b2bdd8957e73ebc2e2c1f2fee35-7cc9b27cf5a64862aabb04a2f3c9e589.webp",
            "href": "/swim-spas"
          },
          {
            "title": "Saunas",
            "body": "Cedar infrared and traditional rooms that fit a garage or patio.",
            "image": "https://pub-987c2295100c458f86a1f7f2be79c41c.r2.dev/clients/8-the-hot-tub-store/astro/categorySaunas-2db5313c8ec41e7a36574631a286199e2e25f3ec18deb402a8475a250ee715c4-bde3cafe41dc4c0c90677d4a09af4de6.webp",
            "href": "/saunas"
          },
          {
            "title": "Cold Plunge",
            "body": "Contrast therapy next to the spa, ready for backyard power.",
            "image": "https://pub-987c2295100c458f86a1f7f2be79c41c.r2.dev/clients/8-the-hot-tub-store/astro/categoryColdPlunge-b40482a9495f3ac2494bd2c50229e619a09f6ffb64401a9cd7e466bb0d790068-0ae8107444b84d4292cd5f47758921ca.webp",
            "href": "/cold-plunges"
          },
          {
            "title": "Massage Chairs",
            "body": "Zero-gravity chairs with heat, stretch, and quiet motors.",
            "image": "https://pub-987c2295100c458f86a1f7f2be79c41c.r2.dev/clients/8-the-hot-tub-store/astro/categoryMassageChairs-7653ffa8e7632079147d0ee6627395d04fa0818e968ad067de5dc19eacb37db7-a111ca272adb429ba8d3a4dfea23d8ad.webp",
            "href": "/massage-chairs"
          }
        ]
      },
      {
        "type": "imagecards",
        "eyebrow": "Find your fit",
        "heading": "Three ways to start",
        "items": [
          {
            "title": "Hot Tubs",
            "body": "Premium seating and hydrotherapy for 4–8 people.",
            "image": "https://pub-987c2295100c458f86a1f7f2be79c41c.r2.dev/clients/8-the-hot-tub-store/assets/hotTubs-e8496d6c8987e896d4eb0eaf12e0b7efaecfeaf9d7b280adac9b11b005f89d62-df153e3395c242a199a2bbafa95d7041.webp",
            "href": "/hot-tubs"
          },
          {
            "title": "Swim Spas",
            "body": "Train, recover, and soak without a pool permit.",
            "image": "https://pub-987c2295100c458f86a1f7f2be79c41c.r2.dev/clients/8-the-hot-tub-store/assets/swimSpas-e608505c26840a904e2b33af294ccf59401e3b2bdd8957e73ebc2e2c1f2fee35-7cc9b27cf5a64862aabb04a2f3c9e589.webp",
            "href": "/swim-spas"
          },
          {
            "title": "Find Your Match",
            "body": "60-second quiz for seats, budget, and backyard access.",
            "image": "https://pub-987c2295100c458f86a1f7f2be79c41c.r2.dev/clients/8-the-hot-tub-store/assets/hero-9900f6745c096443dab6d2513054e5d2501ebcafdbdb9d5270aa1e416193dd06-d09a972bc03e490698837e09b6bdcb8a.webp",
            "href": "/find-your-match"
          }
        ]
      },
      {
        "type": "benefits",
        "heading": "Why neighbors drive to Scottsdale",
        "items": [
          {
            "title": "Try before you buy",
            "body": "Sit in filled spas and feel the jet layout, not a brochure.",
            "icon": null
          },
          {
            "title": "One written total",
            "body": "Delivery, placement, and startup are in the quote.",
            "icon": null
          },
          {
            "title": "Desert-ready setup",
            "body": "We plan shade, pad, and electrical before the truck rolls.",
            "icon": null
          },
          {
            "title": "Local aftercare",
            "body": "Water-care visits and parts from the same team.",
            "icon": null
          }
        ]
      },
      {
        "type": "gallery",
        "heading": "From the showroom and recent installs",
        "images": [
          {
            "src": "https://pub-987c2295100c458f86a1f7f2be79c41c.r2.dev/clients/8-the-hot-tub-store/library/library-aa97e02daba46d7b130628afbae058f2035f66559bbf4ca819c6cc302c4c07e2-0d473df8129c4e6d8ea369d94de4e084.webp",
            "alt": "Showroom floor with filled spas"
          },
          {
            "src": "https://pub-987c2295100c458f86a1f7f2be79c41c.r2.dev/clients/8-the-hot-tub-store/library/library-dc4203acf8cb9d12078c6421a64f9ae3d8bf5bf86ec5e28e08e8bcfce99da32a-0dacb8bf0bec449aa5e2819c9f497d39.webp",
            "alt": "Cedar sauna benches and heater"
          },
          {
            "src": "https://pub-987c2295100c458f86a1f7f2be79c41c.r2.dev/clients/8-the-hot-tub-store/library/library-6433393a5f1fb966534a1151fc440cb7e767f3409943f54f7f48f95b2994ab18-bf3ed4d8aa2c4572856b98ef5ae5a939.webp",
            "alt": "Ice-filled outdoor cold plunge"
          },
          {
            "src": "https://pub-987c2295100c458f86a1f7f2be79c41c.r2.dev/clients/8-the-hot-tub-store/library/library-5be5aa63b82d396b33466c86715d290f2dc35884f23ff0ce1f4b3d6c1dec759e-25049f66d8684631a15191abbfe2d7fd.webp",
            "alt": "Leather massage chair"
          },
          {
            "src": "https://pub-987c2295100c458f86a1f7f2be79c41c.r2.dev/clients/8-the-hot-tub-store/library/library-e467abf26e56bf2d9c71e30c4d9cde1e84cdeb0ad7c631fecb5bd4d6449678e8-14d8f5417d0f4ee59d22bd6571e89062.webp",
            "alt": "Backyard swim spa"
          },
          {
            "src": "https://pub-987c2295100c458f86a1f7f2be79c41c.r2.dev/clients/8-the-hot-tub-store/library/library-d8153d6cb2718ebd499fbcfdec824c2de756d8a8a0cee7d3c43232d1af0be2b6-7dad392dc6a94f6eaf7713d63d50f0ad.webp",
            "alt": "Underwater jet close-up"
          }
        ]
      },
      {
        "type": "reviews",
        "eyebrow": "Reviews",
        "heading": "What Scottsdale families say",
        "items": [
          {
            "name": "Maya R.",
            "quote": "5",
            "rating": 5,
            "source": "Google Review",
            "date": "August 2026",
            "location": null,
            "detail": null
          },
          {
            "name": "Chris T.",
            "quote": "5",
            "rating": 5,
            "source": "Google Review",
            "date": "July 2026",
            "location": null,
            "detail": null
          },
          {
            "name": "Elena V.",
            "quote": "5",
            "rating": 5,
            "source": "Google Review",
            "date": "June 2026",
            "location": null,
            "detail": null
          }
        ],
        "aggregate": {
          "rating": 4.9,
          "count": 186,
          "source": "Google"
        }
      },
      {
        "type": "comparison",
        "eyebrow": "Why buy local",
        "heading": "The Hot Tub Store vs. a crate on a driveway",
        "body": "A spa is a 20-year backyard fixture. The difference is who shows up when the cover needs a clip or the water turns cloudy.",
        "usLabel": null,
        "themLabel": "Online marketplace",
        "rows": [
          {
            "label": "Try before you buy",
            "us": "Filled units on the floor",
            "them": "Photos and a spec sheet"
          },
          {
            "label": "Pricing",
            "us": "One written out-the-door number",
            "them": "Freight, crane, and startup later"
          },
          {
            "label": "Delivery",
            "us": "Local crew that knows North Scottsdale access",
            "them": "Curbside drop"
          },
          {
            "label": "After the sale",
            "us": "A cell phone that a tech answers",
            "them": "A ticket queue"
          }
        ]
      },
      {
        "type": "promise",
        "badgeValue": "100%",
        "badgeLabel": "Written price",
        "heading": "Straight numbers, no weekend close",
        "body": "We would rather send you home to think than push a same-day signature. Come with measurements and leave with a quote you can compare.",
        "bullets": [
          {
            "text": "Out-the-door pricing in writing",
            "superlative": false,
            "footnote": null
          },
          {
            "text": "No pressure, no hidden freight",
            "superlative": false,
            "footnote": null
          },
          {
            "text": "Local delivery and placement plan",
            "superlative": false,
            "footnote": null
          },
          {
            "text": "Water-care walkthrough on day one",
            "superlative": false,
            "footnote": null
          }
        ]
      },
      {
        "type": "splitcards",
        "heading": "Visit the North Scottsdale showroom",
        "items": [
          {
            "title": "Visit the North Scottsdale showroom",
            "body": "18420 N Scottsdale Rd, Suite 110. Park in front. Every category is filled and running — hot tubs, swim spas, saunas, plunges, and chairs.",
            "image": null,
            "showAddress": true,
            "showHours": true,
            "actions": [
              {
                "label": "Get directions",
                "href": "/visit-us",
                "style": "primary"
              }
            ]
          }
        ]
      },
      {
        "type": "splitcards",
        "eyebrow": "Worth the drive",
        "heading": "Two reasons to come in",
        "items": [
          {
            "title": "See them filled and running",
            "body": "Ten minutes in a seat tells you more than an evening of tabs.",
            "image": null,
            "showAddress": true,
            "showHours": true,
            "actions": [
              {
                "label": "Learn more",
                "href": "/inventory",
                "style": "primary"
              }
            ]
          },
          {
            "title": "Talk to people who install them",
            "body": "Ask about pads, 50-amp circuits, and desert covers — you'll get a plan, not a script.",
            "image": null,
            "showAddress": false,
            "showHours": false,
            "actions": [
              {
                "label": "Learn more",
                "href": "/visit-us",
                "style": "primary"
              }
            ]
          }
        ]
      },
      {
        "type": "steps",
        "eyebrow": "How it works",
        "heading": "From first sit to first soak",
        "items": [
          {
            "title": "Come sit in them",
            "body": "Compare models side by side with a specialist who knows the jet maps."
          },
          {
            "title": "Get the out-the-door number",
            "body": "Spa, delivery, placement, and startup — one page you can take home."
          },
          {
            "title": "We handle the rest",
            "body": "Pad check, delivery window, water chemistry, and a local number after."
          }
        ]
      },
      {
        "type": "faq",
        "eyebrow": "Good questions",
        "heading": "What Scottsdale buyers ask first",
        "items": [
          {
            "q": "How much does a hot tub actually cost?",
            "a": "Most four-to-six person spas landed in a backyard here run from the mid $8,000s to the low $20,000s out the door. We quote one number that includes delivery and setup."
          },
          {
            "q": "What does delivery involve?",
            "a": "We measure gates, grade, and overhead lines, then schedule a crew and crane if the side yard is tight. You are not left with a crate on the driveway."
          },
          {
            "q": "What do I need at home?",
            "a": "A level pad and, for most spas, a dedicated 50-amp circuit. Swim spas and saunas have their own needs — we walk those before you buy."
          },
          {
            "q": "Can I finance it?",
            "a": "Yes, through Synchrony Home on qualifying purchases. Checking options in the showroom will not open a hard pull until you apply."
          },
          {
            "q": "Do you deliver outside Scottsdale?",
            "a": "Yes — Phoenix, Paradise Valley, Tempe, Mesa, Chandler, Gilbert, Fountain Hills, and Cave Creek."
          }
        ]
      },
      {
        "type": "ctaband",
        "eyebrow": "Easy monthly options",
        "heading": "See your financing options",
        "body": "Promotional terms on qualifying spas. Check your options in a couple of minutes — asking will not affect your credit.",
        "actions": [
          {
            "label": "Check my options",
            "href": "/financing",
            "style": "primary"
          },
          {
            "label": "Text (480) 555-0180",
            "href": "sms:+14805550180",
            "style": "secondary"
          }
        ],
        "footnote": "Subject to credit approval. Example payments are estimates, not offers of credit.",
        "tone": "dark"
      },
      {
        "type": "cta",
        "heading": "Text us the seats and the budget",
        "buttonLabel": "Request pricing",
        "subtext": "We reply with in-stock matches and a written total. No mailing list, no second salesperson."
      },
      {
        "type": "trust",
        "items": [
          "Family-run since 2014",
          "North Scottsdale showroom",
          "Licensed delivery crew",
          "4.9★ from 186 Google reviews",
          "Written out-the-door pricing"
        ],
        "logos": []
      },
      {
        "type": "bignumber",
        "value": "12+",
        "label": "years helping Valley backyards",
        "claim": null
      },
      {
        "type": "countdown",
        "eyebrow": "Fall showroom event",
        "heading": "Complimentary delivery ends October 31",
        "body": "In-stock spas include Metro Phoenix delivery and a starter chemical kit if you take delivery by the event date.",
        "endsAt": "2026-10-31T17:00:00"
      },
      {
        "type": "ctaband",
        "eyebrow": "Ready when you are",
        "heading": "Come walk the floor this week",
        "body": "Sit in the spas, or start with a text. Either way you get real Scottsdale pricing without the runaround.",
        "actions": [
          {
            "label": "Request pricing",
            "href": "/find-your-match",
            "style": "primary"
          },
          {
            "label": "Get directions",
            "href": "/visit-us",
            "style": "secondary"
          }
        ],
        "footnote": "Open Monday–Saturday, Sunday 11–4. 18420 N Scottsdale Rd, Suite 110.",
        "tone": "dark"
      }
    ],
    "disclosures": []
  },
  "integrations": {
    "d1BindingName": "DB",
    "r2BindingName": "PRODUCT_IMAGES",
    "ghl": {
      "enabled": false
    },
    "meta": {
      "enabled": false
    },
    "zaraz": {
      "enabled": true
    },
    "sentry": {
      "enabled": true
    }
  }
};
